// import { Inter } from "next/font/google";
import { Lato } from "next/font/google";
import "./globals.css";
// import Footer from "@/components/Footer";

// const inter = Inter({ subsets: ["latin"] });

const lato = Lato({
  subsets: ["latin"],
  fontDisplay: "swap",
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  );
}
